name: Generate Snake

on:
  schedule: # Runs the job once a day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the contribution graph snake and save it as a .svg file
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: jinskvarghese
          output: dist/github-contribution-grid-snake.svg

      # Upload the .svg file to the output branch
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
